spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring-eshop
    username: bestuser
    password: bestuser
  flyway:
    baseline-on-migrate: true

