spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-eshop
    username: postgres
    password: bestuser
  flyway:
    baseline-on-migrate: true





